name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
                  
      - name: Add package sources
        run: dotnet nuget add source https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-Labs/nuget/v3/index.json -n CommunityToolkit-Labs

      - name: Restore dependencies
        run: dotnet restore HoroscopeSill.sln

      - name: Build solution
        run: msbuild HoroscopeSill.sln /p:PackageOutputPath=${{ github.workspace }}/artifacts -p:Configuration=Release -p:Platform="Any CPU" -restore:false -m

      - name: Upload Nuget Package
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: ${{ github.workspace }}\artifacts\*.nupkg

      - name: Publish to NuGet
        run: dotnet nuget push "${{ github.workspace }}\artifacts\*.nupkg"  --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json 
